Cupcakes/Models/Bakery.cs
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;


namespace Cupcakes.Models
{
    public class Bakery
    {
        [Key]
        public int BakeryId { get; set; }

        [StringLength(50, MinimumLength = 4)]
        public string BakeryName { get; set; }

        [Range(1, 40)]
        public int Quantity { get; set; }

        [StringLength(50, MinimumLength = 4)]
        public string Address { get; set; }

        public virtual ICollection<Cupcake> Cupcakes { get; set; }
    }
}

Cupcakes/Models/Cupcake.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cupcakes.Models
{
    public class Cupcake
    {
        [Key]
        public int CupcakeId { get; set; }

        [Required(ErrorMessage = "Please select a cupcake type")]
        [Display(Name = "Cupcake Type:")]
        public CupcakeType? CupcakeType { get; set; }

        [Required(ErrorMessage = "Please enter a cupcake description")]
        [Display(Name = "Description:")]
        public string Description { get; set; }

        [Display(Name = "Gluten Free:")]
        public bool GlutenFree { get; set; }

        [Display(Name = "Caloric Value:")]
        public int CaloricValue { get; set; }

        [Range(1, 15)]
        [Required(ErrorMessage = "Please enter a cupcake price")]
        [DataType(DataType.Currency)]
        [Display(Name = "Price:")]
        public double? Price { get; set; }

        [NotMapped]
        [Display(Name = "Cupcake Picture:")]
        public IFormFile PhotoAvatar { get; set; }

        public string ImageName { get; set; }

        public byte[] PhotoFile { get; set; }

        public string ImageMimeType { get; set; }

        [Required(ErrorMessage = "Please select a bakery")]
        public int? BakeryId { get; set; }

        public virtual Bakery Bakery { get; set; }
    }
}

Cupcakes/Models/CupcakeType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cupcakes.Models
{
    public enum CupcakeType
    {
        Birthday,
        Turquoise,
        Chocolate,
        Strawberry
    }
}

Cupcakes/Controllers/CupcakeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Cupcakes.Models;
using Cupcakes.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Cupcakes.Controllers
{
    public class CupcakeController : Controller
    {
        private ICupcakeRepository _repository;
        private IHostingEnvironment _environment;

        public CupcakeController(ICupcakeRepository repository, IHostingEnvironment environment)
        {
            _repository = repository;
            _environment = environment;
        }
        public IActionResult Index()
        {
            return View(_repository.GetCupcakes());
        }

        public IActionResult Details(int id)
        {
            var cupcake = _repository.GetCupcakeById(id);
            if (cupcake == null)
            {
                return NotFound();
            }
            return View(cupcake);
        }

        [HttpGet]
        public IActionResult Create()
        {
            PopulateBakeriesDropDownList();
            return View();
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost(Cupcake cupcake)
        {
            if (ModelState.IsValid)
            {
                _repository.CreateCupcake(cupcake);
                return RedirectToAction(nameof(Index));
            }
            PopulateBakeriesDropDownList(cupcake.BakeryId);
            return View(cupcake);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cupcake cupcake = _repository.GetCupcakeById(id);
            if (cupcake == null)
            {
                return NotFound();
            }
            PopulateBakeriesDropDownList(cupcake.BakeryId);
            return View(cupcake);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(int id)
        {
            var cupcakeToUpdate = _repository.GetCupcakeById(id);
            bool isUpdated = await TryUpdateModelAsync<Cupcake>(
                                     cupcakeToUpdate,
                                     "",
                                     c => c.BakeryId,
                                     c => c.CupcakeType,
                                     c => c.Description,
                                     c => c.GlutenFree,
                                     c => c.Price);
            if (isUpdated == true)
            {
                _repository.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            PopulateBakeriesDropDownList(cupcakeToUpdate.BakeryId);
            return View(cupcakeToUpdate);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var cupcake = _repository.GetCupcakeById(id);
            if (cupcake == null)
            {
                return NotFound();
            }
            return View(cupcake);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _repository.DeleteCupcake(id);
            return RedirectToAction(nameof(Index));
        }
        private void PopulateBakeriesDropDownList(int? selectedBakery = null)
        {
            var bakeries = _repository.PopulateBakeriesDropDownList();
            ViewBag.BakeryID = new SelectList(bakeries.AsNoTracking(), "BakeryId", "BakeryName", selectedBakery);
        }


        public IActionResult GetImage(int id)
        {
            Cupcake requestedCupcake = _repository.GetCupcakeById(id);
            if (requestedCupcake != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedCupcake.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedCupcake.ImageMimeType);
                }
                else
                {
                    if (requestedCupcake.PhotoFile.Length > 0)
                    {
                        return File(requestedCupcake.PhotoFile, requestedCupcake.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Cupcakes/Views/Cupcake/Create.cshtml
@using Cupcakes.Models

@model Cupcakes.Models.Cupcake

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link type="text/css" rel="stylesheet" href="~/css/cupcakes-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="main-titel">Add a Cupcake to the Shop</h1>
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="All"></div>
            <div class="form-field">
                <label asp-for="Bakery"></label>
                <select asp-for="BakeryId" asp-items="ViewBag.BakeryID">
                    <option selected="selected" value="">Select</option>
                </select>
                <span asp-validation-for="BakeryId"></span>
            </div>
            <div class="form-field">
                <label asp-for="CupcakeType"></label>
                <select asp-for="CupcakeType" asp-items="Html.GetEnumSelectList<CupcakeType>()">
                    <option selected="selected" value="">Select</option>
                </select>
                <span asp-validation-for="CupcakeType"></span>
            </div>
            <div class="form-field">
                <label asp-for="Description"></label>
                <textarea asp-for="Description"></textarea>
                <span asp-validation-for="Description"></span>
            </div>
            <div class="form-field">
                <label asp-for="GlutenFree"></label>
                <input asp-for="GlutenFree" />
                <span asp-validation-for="GlutenFree"></span>
            </div>
            <div class="form-field">
                <label asp-for="Price"></label>
                <input asp-for="Price" />
                <span asp-validation-for="Price"></span>
            </div>
            <div class="form-field">
                <label asp-for="CaloricValue"></label>
                <input asp-for="CaloricValue" />
                <span asp-validation-for="CaloricValue"></span>
            </div>
            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" type="file" />
                <span asp-validation-for="PhotoAvatar"></span>
            </div>
            <div class="form-field">
                <input type="submit" value="Submit" />
            </div>
        </form>
    </div>
</body>
</html>

Cupcakes/Views/Cupcake/Delete.cshtml
@model Cupcakes.Models.Cupcake

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <link type="text/css" rel="stylesheet" href="~/css/cupcakes-styles.css" />
</head>
<body>
    <div class="container">
        <h3 class="into">Are you sure you want to delete this?</h3>
        <div class="photo-index-card-details">
            <h3 class="display-picture-title">
                "@Html.DisplayFor(modelItem => modelItem.CupcakeType)"
            </h3>
            @if (Model.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Cupcake", new { Id = Model.CupcakeId })" />
                </div>
            }
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </p>
                <br />
                <p class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.GlutenFree)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.GlutenFree)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Price)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.Price)
                </p>
            </div>
        </div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="CupcakeId" />
            <input type="submit" value="Delete" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</body>
</html>

Cupcakes/Views/Cupcake/Details.cshtml
@model Cupcakes.Models.Cupcake

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <link type="text/css" rel="stylesheet" href="~/css/cupcakes-styles.css" />
</head>
<body>
    <div class="container">
        <div class="photo-index-card-details">
            <h3 class="display-picture-title">
                "@Html.DisplayFor(modelItem => modelItem.CupcakeType)"
            </h3>
            @if (Model.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Cupcake", new { Id = Model.CupcakeId })" />
                </div>
            }
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </p>
                <br />
                <p class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.GlutenFree)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.GlutenFree)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Price)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.Price)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.CaloricValue)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.CaloricValue)
                </p>
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</body>
</html>

Cupcakes/Views/Cupcake/Edit.cshtml
@using Cupcakes.Models
@model Cupcakes.Models.Cupcake

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link type="text/css" rel="stylesheet" href="~/css/cupcakes-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="title">Edit a Cupcake</h1>
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly"></div>
            <input type="hidden" asp-for="CupcakeId" />
            <div class="form-field">
                <label asp-for="Bakery"></label>
                <select asp-for="BakeryId" asp-items="ViewBag.BakeryID">
                    <option selected="selected" value="">Select</option>
                </select>
                <span asp-validation-for="BakeryId"></span>
            </div>
            <div class="form-field">
                <label asp-for="CupcakeType"></label>
                <select asp-for="CupcakeType" asp-items="Html.GetEnumSelectList<CupcakeType>()">
                    <option selected="selected" value="">Select</option>
                </select>
                <span asp-validation-for="CupcakeType"></span>
            </div>
            <div class="form-field">
                <label asp-for="Description"></label>
                <textarea asp-for="Description"></textarea>
                <span asp-validation-for="Description"></span>
            </div>
            <div class="form-field">
                <label asp-for="GlutenFree"></label>
                <input asp-for="GlutenFree" />
                <span asp-validation-for="GlutenFree"></span>
            </div>
            <div class="form-field">
                <label asp-for="Price"></label>
                <input asp-for="Price" />
                <span asp-validation-for="Price"></span>
            </div>
            <div class="form-field">
                <label asp-for="CaloricValue"></label>
                <input asp-for="CaloricValue" />
                <span asp-validation-for="CaloricValue"></span>
            </div>
            <div>
                <input type="hidden" asp-for="ImageMimeType" />
                <input type="hidden" asp-for="ImageName" />
                @Html.HiddenFor(c => c.PhotoAvatar)
                @Html.HiddenFor(c => c.PhotoFile)
            </div>
            <div class="form-field">
                <input type="submit" value="Save" />
            </div>
        </form>
    </div>
</body>
</html>

Cupcakes/Views/Cupcake/Index.cshtml
@model IEnumerable<Cupcakes.Models.Cupcake>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="~/css/cupcakes-styles.css" />
</head>
<body>
    <div class="container">
        <div class="main-title">
            <p class="into">Welcome to our Cupcakes Shop</p>
            <button type="button" onclick="location.href='@Url.Action("Create", "Cupcake")'">Add Cupcake</button>
        </div>
        <div class="img-container">
            @foreach (var item in Model)
            {
                <div class="photo-index-card">
                    <h3 class="display-picture-title">
                        "@Html.DisplayFor(modelItem => item.CupcakeType)"
                    </h3>
                    @if (item.ImageName != null)
                    {
                        <div class="photo-display">
                            <img class="photo-display-img" src="@Url.Action("GetImage", "Cupcake", new { Id = item.CupcakeId })" />
                        </div>
                    }
                    <div>
                        <p class="display-label">
                            @Html.DisplayNameFor(model => item.Description)
                        </p>
                        <br />
                        <p class="display-field">
                            @Html.DisplayFor(model => item.Description)
                        </p>
                    </div>
                    <div>
                        <a asp-action="Edit" asp-route-id="@item.CupcakeId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.CupcakeId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.CupcakeId">Delete</a>
                    </div>
                </div>
            }
        </div>
    </div>

</body>
</html>